**Python for Data Science**

**Practical IX**

Name: HARSHAL SHIRKE

RollNo.: S036

Class: SYIT

Batch: 1

Date of assignment: 30-09-2026

Date of Submission: 30-09-2026

**1. Import a CSV dataset using Pandas.**

In [ ]:
import pandas as pd
df = pd.read_csv("Students.csv")

df.head()

   Roll No    Name Department  Marks  Attendance
0      101   Niraj     BSc IT     78          85
1      102  Vedant     BSc CS     65          90
2      103   Rohit     BSc IT     88          92
3      104  Sumeet     BSc CS     72          80
4      105   Rudra     BSc IT     55          70

**2. Find missing values in the dataset.**

In [ ]:
df.isnull().sum()
missing_values = df.isnull().sum()

print(missing_values[missing_values > 0])

Marks         1
Attendance    1
dtype: int64

**3. Replace missing numerical values with the mean.**

In [ ]:
numerical_columns = df.select_dtypes(include=['number']).columns

df[numerical_columns] = df[numerical_columns].fillna(
    df[numerical_columns].mean()
)

df[numerical_columns].isnull().sum()

Roll No       0
Marks         0
Attendance    0
dtype: int64

**4. Remove duplicate records.**

In [ ]:
print("Duplicate records:", df.duplicated().sum())
df = df.drop_duplicates()
print("Dataset shape:", df.shape)

Duplicate records: 1
Dataset shape: (5, 5)

**5. Display the cleaned dataset.**

In [ ]:
print(df)
df.head(10)

   Roll No   Name Department  Marks  Attendance
0      101   Amit     BSc IT   78.0        85.0
1      102  Priya     BSc CS   65.0        83.8
2      103  Rahul     BSc IT   88.0        92.0
3      104   Neha     BSc CS   72.0        80.0
4      105  Rohan     BSc IT   78.2        70.0

   Roll No   Name Department  Marks  Attendance
0      101   Amit     BSc IT   78.0        85.0
1      102  Priya     BSc CS   65.0        83.8
2      103  Rahul     BSc IT   88.0        92.0
3      104   Neha     BSc CS   72.0        80.0
4      105  Rohan     BSc IT   78.2        70.0